services:
  - type: web
    name: rag-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: TOGETHER_API_KEY
        value: deb14836869b48e01e1853f49381b9eb7885e231ead3bc4f6bbb4a5fc4570b78
      - key: LANGCHAIN_TRACING_V2
        value: "true"
      - key: LANGCHAIN_API_KEY  
        value: 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
